url: "https://www.newbarnltd.co.uk"

plugins:
  - jekyll-sitemap
  - jekyll-toc

collections:
  pages:
    output: true
    permalink: /:name/

exclude:
  - build-jekyll
  - build.sh
  - deploy-neocities
  - LICENSE
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - bin/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - shell.nix
  - vendor
